spring:
    application:
        name: wclient

server:
    port: 8085

eureka:
  port: 8761
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.port}/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  logging:
    pattern:
      level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"